### ISSUE TITLE
Not working with database.db

### ISSUE THREAD

**Issue by TomLewis** [SimonOrJ/CoreProtect-Lookup-Web-Interface#1]
I have set both relative path and full path in settings, no results show on the index, no page reloads, nothing, no checks to tell me its reading it properly, I put the database.db in the same folder as the web UI, which should be ./database.db, I just cant see any results or anything at all.

**Comment by chuushi** [comment]
Hello, sorry for the late reply.

I haven't made any new releases as of now.  I made the error messages appear on the table upon error in the latest commit, but I haven't included it in the latest release (v0.6.x).

Try going to [_CoreProtect Lookup page link_]/conn.php page, and copy-paste what the text is returned.  That should help us know what's causing the error.

**Comment by TomLewis** [comment]
Nothing is returned from this page, it is blank.

**Comment by chuushi** [comment]
It sounds like it might be the configuration error or a PHP exception the code wasn't able to catch.  Do you mind sharing your settings.php file? (with personal info redacted, of course)

**Comment by chuushi** [comment]
You should try the newest release, v0.7.0-beta.  It comes with much better error handling, so that might be able to tell you what's going on.

**Comment by TomLewis** [comment]
Unexpected Error 7: The lookup script was unable to send a proper response.

**Comment by chuushi** [comment]
What version of PHP are you running?  If you're running anything below 5.4, try updating your PHP.  If the problem was with the database, it should return an error about database instead of this error:
    `PDO Exception: SQLSTATE[HY000] [14] unable to open database file`

**Comment by chuushi** [comment]
I just found a problem in the PDO.php file.  The sqlite database file path was built-in as a string instead of as a variable.  I'll try a fix by v0.8.0.

**Comment by chuushi** [comment]
The link problem should be fixed in the v0.8.  Try getting the latest release from here or from the [BukkitDev page](http://dev.bukkit.org/bukkit-plugins/coreprotect-lwi/) and take a note of the PHP version number in the bottom of the page.

If the index page doesn't load from the v0.8.0 or v0.8.1 update, then it is definitely the outdated PHP version.

**Comment by chuushi** [comment]
I'll go ahead and close the issue as the problem should be fixed for most users.  Feel free to open it up again if it's still not resolved.  Thank you for reporting the issue.
~Simon
