### ISSUE TITLE
[request] Search Containers by Lolcation/World & Items by keyword

### ISSUE THREAD

**Issue by TomLewis** [SimonOrJ/CoreProtect-Lookup-Web-Interface#10]
1. Allow us to put in the TPPOS of a container to search for a specific container
2. Allow us to use keywords to search the container for block/item

**Comment by chuushi** [comment]
Hai FrozenBeard, you can now search the containers by world location.  The instructions may not be trivial, but you can:

- Set a coordinate for the container (if just that single container, use "Center" and radius of 0)
- Choose actions of `-Container` and `+container`
- Search specific items by using "Materials" field

The lookup may take a long time (my random test took 40 seconds only to find 4 transactions with a limit of 30).  When searching, I advise use count value near 1 and keep loading more by 1.

Let me know if anything else.  I'll close the ticket for now!

(Commit at close: e5b36f36d79bfcea6891ca0b2f95266ead01b0fd)

**Comment by TomLewis** [comment]
Dope, im still using CoreProtect 2.14.4 on Paper 1.12.2 using MySQL storage, Will this work if I update the web UI?

**Comment by chuushi** [comment]
Yes, that should work!
