### ISSUE TITLE
Giving 777 permission to cache folder is unnecessary and dangerous

### ISSUE THREAD

**Issue by wioxjk** [SimonOrJ/CoreProtect-Lookup-Web-Interface#13]
Giving a folder or file 777 permission is not recommended in any case.
A more suitable permission would setting permission to 744 and change the owner to the correct user the webserver runs as.

Verified that it is working:
https://mc.selea.se/lookup

**Comment by chuushi** [comment]
Yeah, you are correct; that isn't necessary.  The guide was written before I knew more about Linux permissions.
Directory permission of 744 or 774 suffices when the owner is webserver (`www-data:www-data`) or if the webserver is in the group.  In fact, my setup is exactly that.

If you'd like, you can PR updates on the `README.md`.  Else, I will update it as version 1.0.0 comes around completion.

**Comment by wioxjk** [comment]
Alright!
774 permission is actually  unnecessary also, 744 is enough! :)
Looking forward to 1.0.0! Already had good use of this tool, even thou I did'nt manage to get setup.php to work (don't know what's wrong thou).

**Comment by chuushi** [comment]
I removed the cache implementation.  I don't know if cache will be necessary at all, but if anyone thinks otherwise, I guess I can come back to it.  Thank you for the issue! (Commit at close: e5b36f36d79bfcea6891ca0b2f95266ead01b0fd)
