### ISSUE TITLE
Remove information regarding PHP

### ISSUE THREAD

**Issue by wioxjk** [SimonOrJ/CoreProtect-Lookup-Web-Interface#14]
Openly showing which PHP version a site is running does actually help "bad guys" more than it helps the good ones. 
I suggest that this information is removed.

"This webserver is running PHP 5.5.9-1ubuntu4.19."

**Comment by chuushi** [comment]
The site is intended to be visited only by moderators.  I left that there to make submitting bug reports easier.

Anyway, I'll do something about that.  Regardless, people should be using the latest version of PHP whenever possible.

**Comment by chuushi** [comment]
The web app no longer gives PHP information.  Thanks for the issue! (Commit at close: e5b36f36d79bfcea6891ca0b2f95266ead01b0fd)
