### ISSUE TITLE
External Database Login

### ISSUE THREAD

**Issue by PenguinNexus** [SimonOrJ/CoreProtect-Lookup-Web-Interface#16]
Hey there,

Is there any way to use an External Database to set up login information? Need to be able to limit it to usergroup ID as well, so only game admins can access it.

Kind Regards,
Penguin

**Comment by chuushi** [comment]
I'll be working on this project as soon as I'm done with my finals (next week).  I've been very busy with classes this semester, so I couldn't work on this as much for past few months.

I am looking into adding OAuth2 (Google, GitHub, etc) login as requested in issue #3.  If you're looking into specific login database, please tell me more!

~Simon

**Comment by chuushi** [comment]
Hi @PenguinNexus!  If you're still looking into this, which external database were you referring to for the logins?

**Comment by brotherxaos** [comment]
> Hi @PenguinNexus! If you're still looking into this, which external database were you referring to for the logins?

Hi @chuushi I'm not that guy, but I saw your post on reddit, and have this installed now, and thought I had all the information in the config.php file for my external mysql database, but it gives an error when I try to do a lookup. Is there a way to check the more detailed error message? That all assumes that I can connect to the remote DB using this tool in the first place. :)

**Comment by chuushi** [comment]
Hi @brotherxaos!  Please make a new issue regarding it since this issue doesn't relate to error messages.  Please show me the error message, and if it gives a JSON error, follow the instructions I laid out in #25 for now to check the specifics of the error.
