### ISSUE TITLE
Error 5: CoreProtect too old. Update to v2.11 or above.

### ISSUE THREAD

**Issue by iTzEthqnHD** [SimonOrJ/CoreProtect-Lookup-Web-Interface#17]
im getting a "Error 5: CoreProtect too old. Update to v2.11 or above." but my core protect is a new version. Does this need to be updated?

**Comment by iTzEthqnHD** [comment]
bump?

**Comment by chuushi** [comment]
I haven't any time to update the code in a while...  It's not tested with latest version yet.
This project's on my backlog right now as I'm in school right now.

Basically, the code needs updating and rewriting to work with latest version of CoreProtect. :I

**Comment by iTzEthqnHD** [comment]
Ok, do you have a clue of when you might be able to update it? Thank you for your time!

**Comment by chuushi** [comment]
I honestly have no clue.  All I can do is try and find time and motivation after this semester's over.

**Comment by chuushi** [comment]
The code is updated, and the error you mentioned should not come up anymore (Provided you're using CoreProtect version 2.12.0 or above).  Thank you for the issue!  (Commit at close: e5b36f36d79bfcea6891ca0b2f95266ead01b0fd)
