### ISSUE TITLE
There was a massive CoreProtect update for 1.13

### ISSUE THREAD

**Issue by TomLewis** [SimonOrJ/CoreProtect-Lookup-Web-Interface#18]
The only way I use CoreProtect is via this amazing webUI, There is no alternative for quickly searching for information from a webUI, will you be updating for the new 1.13? please.

**Comment by chuushi** [comment]
I hope to come back to this, but I don't recognize the code I wrote two years ago 😐 

I'll try working on it next month, but I can't make any guarantees yet.

**Comment by snarfattack** [comment]
So far, I'm able to search against 1.13 database, but I've only done basic searches as I just found this. What's broken?

**Comment by chuushi** [comment]
AFAIK I haven't added proper support for detecting player deaths, which was added to CoreProtect sometime after the latest beta of this was released.  That's the only missing feature I can think of.

**Comment by chuushi** [comment]
I've done a whole lot of rewriting for this project.  For now, I'll have to drop support for older versions of CoreProtect.

I will test and support older versions them once I get the code working for the latest version.

Sorry it took so long before I came back to this!

**Comment by chuushi** [comment]
The app now works with the latest version of CoreProtect.  Thank you for the issue!  (Commit at close: e5b36f36d79bfcea6891ca0b2f95266ead01b0fd)
