### ISSUE TITLE
World filter doesn't work with Coords filter

### ISSUE THREAD

**Issue by snarfattack** [SimonOrJ/CoreProtect-Lookup-Web-Interface#19]
```
       if (isset($coord)) $filter['coord'] .= " AND ";
        else               $filter['coord'] = "";
                           $filter['coord'] .= "wid=".$Cc->getId($q['wid'],"world");
```

If evaluation will always resolve to false since $coord does not exist, the code should be:

```
        if (isset($filter['coord'])) $filter['coord'] .= " AND ";
        else $filter['coord'] = "";
        $filter['coord'] .= "wid=".$Cc->getId($q['wid'],"world");
```

**Comment by chuushi** [comment]
I have since rewritten the code to handle them separately.  The world and coords filters should be independent of each other in the latest version!

**Comment by chuushi** [comment]
Coordinates and worlds now gets looked up independently of each other.  Thank you for the issue! (Commit at close: e5b36f36d79bfcea6891ca0b2f95266ead01b0fd)
