### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Fargus-Van-Crystal-de-Mindark** [SimonOrJ/CoreProtect-Lookup-Web-Interface#25]
Good Morning, there is an error when that don't let u login .

SyntaxError: Unexpected token < in JSON at position 4

I digit the username and password and when I confirm I have this error

**Comment by chuushi** [comment]
Good morning!

Looks like there's a PHP error.  Try:

- Open to the CoreProtect page
- press [F12] to open the developer console
- go to the 'networking' tab
![image](https://user-images.githubusercontent.com/13530989/82263549-287dc600-9931-11ea-8cda-bd1196179726.png)
- then try logging in
- after that, go to the 'response' tab and copy-paste the contents within there.
![image](https://user-images.githubusercontent.com/13530989/82263599-45b29480-9931-11ea-8804-e408b52e169b.png)

This is the best debugging tool we have at the moment, and I hope to make this debugging process easier in the later pre-releases.

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
I've this one:

` <svg xmlns='http://www.w3.org/2000/svg' width='30' height='30' viewBox='0 0 30 30'><path stroke='rgba(255, 255, 255, 0.5)' stroke-linecap='round' stroke-miterlimit='10' stroke-width='2' d='M4 7h22M4 15h22M4 23h22'/></svg>`

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
And this one:

`<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1" />
    <link rel="shortcut icon" href="/F9CD80F3-B79B-49AB-AD16-6F61BFFFC81B/netdefender/alert/images/bdicon.ico" type="image/x-icon" />
    <title>Protection Web par Bitdefender</title>
    <link rel="stylesheet" href="/F9CD80F3-B79B-49AB-AD16-6F61BFFFC81B/netdefender/alert/css/tl_style.css" type="text/css" media="all" charset="utf-8" />
</head>

<body>

    <div class="threat-blocked-view">

        <div class="threat-blocked-container">
            <div class="threat-blocked">
                <div class="header">
                    <div class="logo">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60">
                            <path fill="#d0021b" d="M31.69,32.44H26V42.2h5.46c3,0,7.28-.52,7.28-5C38.74,33.68,36.48,32.44,31.69,32.44Z" />
                            <path fill="#d0021b" d="M53.91,0H6.09A6.09,6.09,0,0,0,0,6.08V53.92A6.09,6.09,0,0,0,6.09,60H53.91A6.09,6.09,0,0,0,60,53.92V6.08A6.09,6.09,0,0,0,53.91,0ZM32.09,47.46l-10.86,0V18.79c0-1.55-1.45-1.75-3.51-3.46L16,13.87v-.54H33.08c5,0,10.19,2.36,10.19,8.58,0,3.86-2.3,6.4-5.75,7.46v.1a8.07,8.07,0,0,1,7.22,8.25C44.74,45.16,38.41,47.46,32.09,47.46Z" />
                            <path fill="#d0021b" d="M36.22,25.76a3.79,3.79,0,0,0,1.15-2.82A3.9,3.9,0,0,0,36.26,20c-1-1-2-1.43-5.35-1.43H26v8.59h5.42C33.89,27.18,35.24,26.71,36.22,25.76Z" />
                        </svg>
                    </div>

                    <h1>
                        <span>Protection Web par </span>Bitdefender
                    </h1>

                </div>

                <div id="kucb_4a5402819cf7959b1960f9d18dfd769f_id_alert_content">
                    <div class="body">
                        <h2>Cette page est bloquée pour votre sécurité</h2>
                        <span class="muted" id="kucb_4a5402819cf7959b1960f9d18dfd769f_id_url"></span>
                        <p>Une tentative d’envoi de votre mot de passe non chiffré, en texte brut, a été empêchée sur cette page. Vous trouverez plus de détails dans la section Notifications de votre solution de sécurité Bitdefender.</p>
                    </div>

                    <div class="footer">
                        <button class="primary-btn" id="kucb_4a5402819cf7959b1960f9d18dfd769f_id_goToHomePage">Retour en toute sécurité</button>
                        <a href="" class="link-btn" id="kucb_4a5402819cf7959b1960f9d18dfd769f_id_proceedAnyway">Je comprends les risques, je souhaite quand même consulter cette page</a>
                        <div id="kucb_4a5402819cf7959b1960f9d18dfd769f_id_whitelist">
    <span class="small muted">Si vous êtes certain(e) que cette page n'est pas dangereuse, vous pouvez <a href="" id=" kucb_4a5402819cf7959b1960f9d18dfd769f_id_add2whitelist">l'ajouter à votre Liste des exceptions</a> recensant des sites Internet de confiance. Attention, vous ne serez plus averti(e) en cas de menace sur cette page.</span>
</div>

                    </div>
                </div>
                
            </div>

        </div>

    </div>


<script id="kucb_4a5402819cf7959b1960f9d18dfd769f_script" type="text/javascript">
    var kucb_4a5402819cf7959b1960f9d18dfd769f_TIMEOUT = 1000;
    var kucb_4a5402819cf7959b1960f9d18dfd769f_timeoutID = -1;
    var kucb_4a5402819cf7959b1960f9d18dfd769f_action;
    var kucb_4a5402819cf7959b1960f9d18dfd769f_haspassword=false;

	(function (undefined) {
	
		function encodeString(str) {
			var temp = [];
			var length = str.length;
			for (var i = 0; i < length; i++) {
				//obtain character code
				var code = str.charCodeAt(i);
				if (code >= 0xD800 && code <=0xDBFF) {
					var high = code;
					var low = str.charCodeAt(i+1);
					if (isNaN(low)) {
						//We hit the end of the string. Just skip this last character
						continue;
					}
					code = (high - 0xD800) * 0x400 + (low - 0xDC00) + 0x10000;
				}
			
				temp.push(["&#", code, ";"].join(''));
			}
			return temp.join('');
		}
	
		function kucb_4a5402819cf7959b1960f9d18dfd769f_goToHomePage() {
			if (typeof window.home == 'function') {
				window.home();
			} else { // For IE
				window.location = 'about:blank';
			}
		}

		function kucb_4a5402819cf7959b1960f9d18dfd769f_showpassword(show) {
		    if (show) {
		        document.getElementById("kucb_4a5402819cf7959b1960f9d18dfd769f_id_alert_content").style.display = "none";
		        document.getElementById("kucb_4a5402819cf7959b1960f9d18dfd769f_id_password_error").style.display = "none";
		        document.getElementById("kucb_4a5402819cf7959b1960f9d18dfd769f_id_password_content").style.display = "block";
		        document.getElementById("kucb_4a5402819cf7959b1960f9d18dfd769f_id_password").value = "";
		        kucb_4a5402819cf7959b1960f9d18dfd769f_haspassword=true;
		    } else {
		        document.getElementById("kucb_4a5402819cf7959b1960f9d18dfd769f_id_alert_content").style.display = "block";
		        var elem = document.getElementById("kucb_4a5402819cf7959b1960f9d18dfd769f_id_password_content");
		        if (elem) {
		            elem.style.display = "none";
		        }
		        kucb_4a5402819cf7959b1960f9d18dfd769f_haspassword=false;
		    }
		}

		function kucb_4a5402819cf7959b1960f9d18dfd769f_proceed() {
		    var obj_ajax = null;
		    (window.ActiveXObject) ? obj_ajax = new ActiveXObject("Microsoft.XMLHTTP") : obj_ajax = new XMLHttpRequest();
		    if (obj_ajax) {
		        obj_ajax.onreadystatechange = function () {
		            if ((obj_ajax.readyState == 4) && (obj_ajax.status == 200)) {
		                if (kucb_4a5402819cf7959b1960f9d18dfd769f_timeoutID != -1) {
                            clearTimeout(kucb_4a5402819cf7959b1960f9d18dfd769f_timeoutID);
		                    kucb_4a5402819cf7959b1960f9d18dfd769f_timeoutID = -1;
		                }
		                var response = obj_ajax.getResponseHeader("BDWL_D0D57627257747A3B2EE8E4C3B86CBA3");
		                if (response == "1") { // create
		                    kucb_4a5402819cf7959b1960f9d18dfd769f_showpassword(false);
		                    kucb_4a5402819cf7959b1960f9d18dfd769f_timeoutID = setTimeout(kucb_4a5402819cf7959b1960f9d18dfd769f_proceed, kucb_4a5402819cf7959b1960f9d18dfd769f_TIMEOUT);
		                } else if (response == "2") { // pending
		                    kucb_4a5402819cf7959b1960f9d18dfd769f_timeoutID = setTimeout(kucb_4a5402819cf7959b1960f9d18dfd769f_proceed, kucb_4a5402819cf7959b1960f9d18dfd769f_TIMEOUT);
		                } else if (response == "3") { // yes
		                    window.location.reload();
		                } else if (response == "4") { // no
		                    kucb_4a5402819cf7959b1960f9d18dfd769f_showpassword(false);
		                } else if (response == "5") { // has-password
		                    kucb_4a5402819cf7959b1960f9d18dfd769f_showpassword(true);
		                } else if (response == "6") { // request-password
		                    kucb_4a5402819cf7959b1960f9d18dfd769f_showpassword(true);
		                } else if (response == "7") { // password-error
		                    var epe = document.getElementById("kucb_4a5402819cf7959b1960f9d18dfd769f_id_password_error");
		                    if (epe) {
		                        epe.style.display = "block"; }
		                } else if (response == "8") { // password-expired
		                    kucb_4a5402819cf7959b1960f9d18dfd769f_showpassword(false);
		                    var epa = document.getElementById("kucb_4a5402819cf7959b1960f9d18dfd769f_id_proceedAnyway");
		                    if (epa) {
		                        epa.style.display = "none"; }
		                    var ewl = document.getElementById("kucb_4a5402819cf7959b1960f9d18dfd769f_id_whitelist");
		                    if (ewl) {
		                        ewl.style.display = "none"; }
		                } else if (response == "9") { // obk
		                    window.location.reload();
		                } 
		            }
		        }

		        var params = encodeURIComponent(window.location);
		        sid = "" + Math.random();
		        obj_ajax.open("POST", sid, true);
		        obj_ajax.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
		        obj_ajax.setRequestHeader("BDNDSS_B67EA559F21B487F861FDA8A44F01C50", "NDSECK_2d6facd7dab626bd705f2fd7c9a7a0e7");
		        obj_ajax.setRequestHeader("BDNDCA_BBACF84D61A04F9AA66019A14B035478", "NDCA_2d6facd7dab626bd705f2fd7c9a7a0e7");
		        obj_ajax.setRequestHeader("BDNDTK_BTS86RE4PDHKKZYVUJE2UCM87SLSUGYF", "136123098827fd7821e9d56a4d6ae09622e33013fe2536120cb1bfe91c318323");
		        obj_ajax.setRequestHeader("BDWL_D0D57627257747A3B2EE8E4C3B86CBA3", "4a5402819cf7959b1960f9d18dfd769f");
		        obj_ajax.setRequestHeader("BDPID_A381AA0A15254C36A72B115329559BEB", "20308");
		        obj_ajax.setRequestHeader("BDNDWB_5056E556833D49C1AF4085CB254FC242", kucb_4a5402819cf7959b1960f9d18dfd769f_action);
		        if (kucb_4a5402819cf7959b1960f9d18dfd769f_haspassword) {
                    obj_ajax.setRequestHeader("BDPWD_B030436C9F234E61BBECEDA8AC84FB1E", document.getElementById("kucb_4a5402819cf7959b1960f9d18dfd769f_id_password").value);
                }
		        obj_ajax.send(params);
		    }
		}

        function kucb_4a5402819cf7959b1960f9d18dfd769f_password_btnOk() {
            var p = document.getElementById("kucb_4a5402819cf7959b1960f9d18dfd769f_id_password").value;
            if (!p) {
                return; }
            kucb_4a5402819cf7959b1960f9d18dfd769f_proceed();
        }

        function kucb_4a5402819cf7959b1960f9d18dfd769f_password_btnCancel() {
            kucb_4a5402819cf7959b1960f9d18dfd769f_showpassword(false);
        }

		function setUrl() {
		    var elem = document.getElementById("kucb_4a5402819cf7959b1960f9d18dfd769f_id_url");
		    if (elem) {
		        elem.innerHTML = encodeString(window.location.href);
		    }
		}

		function setupClickListener(id, callback) {
			var elem = document.getElementById(id);
			//Disable click functions
			if (elem) {
				elem.addEventListener("click", function(event) {
					event.preventDefault();
					event.stopPropagation();
					if (event.isTrusted) {
						callback(event);
					}
				});
			}
		}
		
		function setupSubmitListener(id, callback) {
			var elem = document.getElementById(id);
			if (elem) {
				elem.addEventListener("submit", function(event) {
					event.preventDefault();
					event.stopPropagation();
					if (event.isTrusted) {
						callback(event);
					}
				});
			}
		}

		setUrl();

		setupClickListener("kucb_4a5402819cf7959b1960f9d18dfd769f_id_goToHomePage", function(){
			kucb_4a5402819cf7959b1960f9d18dfd769f_goToHomePage();
			return false;
		});

		setupClickListener("kucb_4a5402819cf7959b1960f9d18dfd769f_id_proceedAnyway", function(){
		    kucb_4a5402819cf7959b1960f9d18dfd769f_action = "cl.proceedanyway"; 
		    kucb_4a5402819cf7959b1960f9d18dfd769f_proceed();
			return false;
		});

		setupClickListener("kucb_4a5402819cf7959b1960f9d18dfd769f_id_add2whitelist", function(){
		    kucb_4a5402819cf7959b1960f9d18dfd769f_action = "add2whitelist";
		    kucb_4a5402819cf7959b1960f9d18dfd769f_proceed();
			return false;
		});

		setupClickListener("kucb_4a5402819cf7959b1960f9d18dfd769f_id_password_goToHomePage", function(){
		    kucb_4a5402819cf7959b1960f9d18dfd769f_goToHomePage();
		    return false;
		});

		setupClickListener("kucb_4a5402819cf7959b1960f9d18dfd769f_id_password_btnOk", function(){
		    kucb_4a5402819cf7959b1960f9d18dfd769f_password_btnOk();
		    return false;
		});
		
		setupSubmitListener("kucb_4a5402819cf7959b1960f9d18dfd769f_id_password_form", function(){
		    kucb_4a5402819cf7959b1960f9d18dfd769f_password_btnOk();
		    return false;
		});

		setupClickListener("kucb_4a5402819cf7959b1960f9d18dfd769f_id_password_btnCancel", function(){
		    kucb_4a5402819cf7959b1960f9d18dfd769f_password_btnCancel();
		    return false;
		});
		
		kucb_4a5402819cf7959b1960f9d18dfd769f_action = "running";
		kucb_4a5402819cf7959b1960f9d18dfd769f_proceed();

		var script_elem = document.getElementById("kucb_4a5402819cf7959b1960f9d18dfd769f_script");
		script_elem.parentNode.removeChild(script_elem);
	})();

</script>
</body>
</html>`

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
If u cannot understand from all of this... the code is horrible here....
I give you the link

[http://survivalla.fun/coreprotect/](url)

**Comment by chuushi** [comment]
![image](https://user-images.githubusercontent.com/13530989/82270815-fd50a200-9943-11ea-9af2-c954ad2fb6ac.png)

Can you try copy-pasting the contents of this instead?  Those look like the text you provided are from another website or browser extension.

I don't know what the credentials are, so I can't say for sure.  The login seems to fail successfully, though.

![image](https://user-images.githubusercontent.com/13530989/82270872-36891200-9944-11ea-92cf-994a24611b06.png)

Thanks!

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
http://survivalla.fun/coreprotect/

username: Fargus
Password: 123456

**Comment by chuushi** [comment]
I logged in successfully.

What browser and extensions are you using? It's possible that your browser is erroring something on your side.  Maybe because you're trying to send the password over non-secure protocol (HTTP)?

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
Yes, maybe is the antivirus
I try disabling it in these page.

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
Yes it was this. I needed to disable a security block that the Antivirus gave to me as a "dangerous attack to my personal life"

-_-

**Comment by chuushi** [comment]
I'd suggest you look into setting up HTTPS on your webserver.  If you're self-hosting the webserver, look up how to set up LetsEncrypt in your free time. ^^
In any case, I'm glad to be of help to ya.  Let me know if you have any other issues, or feel free to close the issue.   Thanks for the issue!

**Comment by Fargus-Van-Crystal-de-Mindark** [comment]
Thanks you 👍
