### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0 (Possible webserver PHP misconfiguration)

### ISSUE THREAD

**Issue by 127p** [SimonOrJ/CoreProtect-Lookup-Web-Interface#28]
Hello,

When trying to make a search I receive the error:

`SyntaxError:` Unexpected token < in JSON at position 0 (Possible webserver PHP misconfiguration)

I'm using sqlite, the database is in the same folder than index.php so my config file looks like this:

```
'database' => [
    'server' => [
        'type'        => 'sqlite',
        'path'        => 'database.db',
        'host'        => '',
        'database'    => '',
        'username'    => '',
        'password'    => '',
        'flags'       => '',
        'prefix'      => 'co_',
        'preBlockName'=> true,
        'mapLink'     => 'https://localhost:8123/?worldname={world}&mapname=surface&zoom=3&x={x}&y={y}&z={z}'
    ],
],
```

I'm using XAMPP on my windows 10 computer to make the php server with the defaults settings, am I missing some configuration of php.ini?

Thanks!

**Comment by chuushi** [comment]
You might be missing some extensions.  Check [the prerequisites](https://github.com/chuushi/CoreProtect-Lookup-Web-Interface#prerequisites) and see if you have those modules enabled!

**Comment by guimartino** [comment]
I'm facing the same issue, but using mysql
I did a double check and I have PDO_MYSQL installed on my webservice and all the connection info are correct

![image](https://user-images.githubusercontent.com/3578494/85195141-90179000-b2a6-11ea-82a2-848ec1386354.png)

At the same server I'm able to do PDO queries in the same Mysql server (using the same credentials)

What can be happening in this case?
Many thanks! :)

**Comment by cokeramirez** [comment]
![image](https://user-images.githubusercontent.com/7583931/85254623-ba945500-b42e-11ea-8b55-7f2dbc2b81cd.png)

We also have PDO activated and have the same issue, but we are using sqlite.

Is there any other setting I should check?

**Comment by chuushi** [comment]
Huh, that is interesting.  I'd like to narrow down the variables and test it on a setup similar to your environment.  What version of PHP and webserver are you using?

**Comment by 127p** [comment]
XAMPP 7.4.7 / PHP 7.4.7 Last version, Default install
https://www.apachefriends.org/es/index.html
