### ISSUE TITLE
Error on lookup

### ISSUE THREAD

**Issue by ntimo** [SimonOrJ/CoreProtect-Lookup-Web-Interface#4]
Hi, 
I just updated to the new version and everytime I now make lookup I get this error: 
Unexpected Error 7: The lookup script was unable to send a proper response.

Please note: I replaced some thinks with xxxxxxxxxxx 

This is written in the server logs:
AH01071: Got error 'PHP message: PHP Warning: require(ChromePhp.php): failed to open stream: No such file or directory in /var/www/vhosts/xxxxxxxxxxxxxxx/conn.php on line 30\nPHP message: PHP Fatal error: require(): Failed opening required 'ChromePhp.php' (include_path='.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/xxxxxxxxxxxxx/conn.php on line 30\n', referer: https://xxxxxxxxxxxxxxxx/

**Comment by chuushi** [comment]
Oh shoot, I forgot to comment out https://github.com/SimonOrJ/CoreProtect-Lookup-Web-Interface/blob/master/web/conn.php#L30

**Comment by chuushi** [comment]
Ok, it should be fixed.  Thanks for the issue!
