### ISSUE TITLE
Hosting a second demo?

### ISSUE THREAD

**Issue by ntimo** [SimonOrJ/CoreProtect-Lookup-Web-Interface#8]
Hi there,
I would be happy to host a second demo if you want.

Thank you,
Timo

**Comment by chuushi** [comment]
The demo has data donated by the admins of two separate servers.  If you want your server to be included there, feel free to shoot me an email.  My email is in my profile.

If you want to run it in your server and demo a different language, you can include the link to there in the email.

~Simon

**Comment by ntimo** [comment]
I mailed you, if you like we can discuss the details via email?

Timo
